# docker-compose.yml
services:
  # Build service for React application
  react-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - build_volume:/app/dist
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  # Nginx service for serving the built application
  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - build_volume:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - react-build
networks:
  app-network:
    driver: bridge

volumes:
  build_volume:
