# docker-compose.yml
services:
  # Build service for React application
  react-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - build_volume:/app/dist
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  certbot:
    image: certbot/certbot
    container_name: certbot-container
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/lib:/var/lib/letsencrypt
      - ./nginx/html:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"

  # Nginx service for serving the built application
  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT:-80}:80"
      - "443:443"
    volumes:
      - build_volume:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - react-build
networks:
  app-network:
    driver: bridge

volumes:
  build_volume:
