version: "3.8"

services:
  chatapp:
    container_name: chatapp-react
    image: web-chat
    
    build:
      context: .

    networks:
      - default
    
    volumes:
      - ./src:/app/src
    ports:
      - "5173:3000"

networks:
  default:
      
